@extends('layouts.app')
@section('title', 'Expediente clínico')
@section('content')
@php
    $tab = request('tab', 'resumen');
    $isDoctor = session('access_role') === 'doctor';
    $medical = $patient->medicalHistory;
    $emergency = $patient->contacto_emergencia ?? [];
    $teeth = $patient->odontogramEntries->keyBy('tooth_number');
    $colors = ['Sano'=>'bg-emerald-50 border-emerald-300 text-emerald-700','Caries'=>'bg-rose-50 border-rose-300 text-rose-700','Restaurado'=>'bg-sky-50 border-sky-300 text-sky-700','Ausente'=>'bg-slate-100 border-slate-300 text-slate-400','Corona'=>'bg-amber-50 border-amber-300 text-amber-700','Implante'=>'bg-violet-50 border-violet-300 text-violet-700','Endodoncia'=>'bg-orange-50 border-orange-300 text-orange-700'];
@endphp
<div class="space-y-6">
    <header class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div class="flex items-center gap-4"><span class="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#eeecff] text-xl font-bold text-[#7065f0]">{{ mb_strtoupper(mb_substr($patient->nombre,0,1)) }}</span><div><p class="text-sm font-semibold text-[#7065f0]">Expediente #{{ str_pad($patient->id,5,'0',STR_PAD_LEFT) }}</p><h1 class="text-3xl font-bold">{{ $patient->nombre }}</h1><p class="text-sm text-slate-500">{{ $patient->email ?: 'Sin correo' }} · {{ $patient->telefono ?: 'Sin teléfono' }}</p></div></div>
        <div class="flex gap-2"><a href="{{ route('pacientes.edit',$patient) }}" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Editar paciente</a><a href="{{ route('pacientes') }}" class="rounded-xl bg-slate-800 px-4 py-2.5 text-sm font-semibold text-white">Volver</a></div>
    </header>
    @if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
    <nav class="flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5">
        @foreach(['resumen'=>'Resumen','consultas'=>'Consultas','antecedentes'=>'Antecedentes','odontograma'=>'Odontograma','citas'=>'Citas'] as $key=>$label)<a href="{{ route('pacientes.expediente',['paciente'=>$patient,'tab'=>$key]) }}" class="whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold {{ $tab===$key?'bg-[#7065f0] text-white':'text-slate-500 hover:bg-slate-50' }}">{{ $label }}</a>@endforeach
    </nav>

    @if($tab==='resumen')
        <section class="grid gap-4 md:grid-cols-3">
            <article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs font-bold uppercase text-slate-400">Estado</p><p class="mt-3 text-xl font-bold">{{ $patient->estado }}</p><p class="mt-1 text-xs text-slate-400">Última visita: {{ $patient->ultima_visita?->format('d/m/Y') ?? 'Sin registro' }}</p></article>
            <article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs font-bold uppercase text-slate-400">Alertas médicas</p><p class="mt-3 text-sm font-semibold {{ $medical?->allergies?'text-rose-600':'text-emerald-600' }}">{{ $medical?->allergies ?: 'Sin alergias registradas' }}</p><p class="mt-2 text-xs text-slate-400">{{ $medical?->conditions ?: 'Sin padecimientos registrados' }}</p></article>
            <article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs font-bold uppercase text-slate-400">Próxima cita</p>@if($nextAppointment)<p class="mt-3 text-xl font-bold">{{ $nextAppointment->date->format('d/m/Y') }}</p><p class="text-xs text-slate-500">{{ date('H:i',strtotime($nextAppointment->time)) }} · {{ $nextAppointment->tipo }}</p>@else<p class="mt-3 text-sm text-slate-400">Sin cita programada</p>@endif</article>
        </section>
        <section class="grid gap-5 lg:grid-cols-2">
            <article class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-bold">Datos personales</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt class="text-xs text-slate-400">Correo</dt><dd class="font-semibold">{{ $patient->email?:'No registrado' }}</dd></div><div><dt class="text-xs text-slate-400">Teléfono</dt><dd class="font-semibold">{{ $patient->telefono?:'No registrado' }}</dd></div><div class="col-span-2"><dt class="text-xs text-slate-400">Dirección</dt><dd class="font-semibold">{{ $patient->direccion?:'No registrada' }}</dd></div><div><dt class="text-xs text-slate-400">Seguro</dt><dd class="font-semibold">{{ $patient->seguro?:'Sin seguro' }}</dd></div><div><dt class="text-xs text-slate-400">Póliza</dt><dd class="font-semibold">{{ $patient->poliza?:'No registrada' }}</dd></div></dl></article>
            <article class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-bold">Contacto de emergencia</h2><div class="mt-5 rounded-xl bg-slate-50 p-4"><p class="font-semibold">{{ $emergency['nombre']??'No registrado' }}</p><p class="text-sm text-slate-500">{{ $emergency['relacion']??'' }}</p><p class="mt-2 text-sm font-semibold text-[#7065f0]">{{ $emergency['telefono']??'' }}</p></div><div class="mt-5 flex justify-between text-xs text-slate-400"><span>Consultas clínicas</span><strong class="text-slate-700">{{ $patient->clinicalRecords->count() }}</strong></div></article>
        </section>
    @elseif($tab==='consultas')
        <div class="grid gap-5 xl:grid-cols-[.8fr_1.3fr]">
            @if($isDoctor)<form method="POST" action="{{ route('pacientes.clinical.store',$patient) }}" class="h-fit rounded-2xl border border-slate-200 bg-white p-6">@csrf<h2 class="font-bold">Nueva nota clínica</h2><div class="mt-5 space-y-4"><label class="block text-xs font-bold">Fecha y hora<input type="datetime-local" name="recorded_at" value="{{ now()->format('Y-m-d\TH:i') }}" required class="mt-2 w-full rounded-xl border border-slate-200 p-3"></label><label class="block text-xs font-bold">Motivo<input name="reason" required class="mt-2 w-full rounded-xl border border-slate-200 p-3"></label>@foreach(['diagnosis'=>'Diagnóstico','procedure'=>'Procedimiento','prescription'=>'Receta e indicaciones','notes'=>'Notas'] as $name=>$label)<label class="block text-xs font-bold">{{ $label }}<textarea name="{{ $name }}" rows="2" class="mt-2 w-full rounded-xl border border-slate-200 p-3"></textarea></label>@endforeach<label class="block text-xs font-bold">Próxima revisión<input type="date" name="next_visit" class="mt-2 w-full rounded-xl border border-slate-200 p-3"></label><button class="w-full rounded-xl bg-[#7065f0] p-3 text-sm font-bold text-white">Guardar nota clínica</button></div></form>@endif
            <section class="space-y-3 {{ !$isDoctor?'xl:col-span-2':'' }}">@forelse($patient->clinicalRecords as $record)<article class="rounded-2xl border border-slate-200 bg-white p-5"><div class="flex justify-between"><div><p class="text-xs font-bold text-[#7065f0]">{{ $record->recorded_at->format('d/m/Y · H:i') }}</p><h3 class="mt-1 font-bold">{{ $record->reason }}</h3></div><span class="text-xs text-slate-400">{{ $record->dentist?->nombre }}</span></div><div class="mt-4 grid gap-3 sm:grid-cols-2">@if($record->diagnosis)<div><b class="text-[10px] uppercase text-slate-400">Diagnóstico</b><p class="text-sm">{{ $record->diagnosis }}</p></div>@endif @if($record->procedure)<div><b class="text-[10px] uppercase text-slate-400">Procedimiento</b><p class="text-sm">{{ $record->procedure }}</p></div>@endif @if($record->prescription)<div class="sm:col-span-2 rounded-xl bg-indigo-50 p-3 text-sm text-indigo-800">{{ $record->prescription }}</div>@endif</div></article>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-400">Sin consultas clínicas.</div>@endforelse</section>
        </div>
    @elseif($tab==='antecedentes')
        <form method="POST" action="{{ route('pacientes.medical.update',$patient) }}" class="rounded-2xl border border-slate-200 bg-white p-6">@csrf @method('PUT')<div class="flex justify-between"><div><h2 class="font-bold">Antecedentes médicos</h2><p class="text-xs text-slate-400">Información importante antes de cualquier procedimiento.</p></div>@if(!$isDoctor)<span class="text-xs text-slate-400">Solo lectura</span>@endif</div><div class="mt-6 grid gap-5 md:grid-cols-2"><label class="text-xs font-bold">Tipo de sangre<input name="blood_type" value="{{ $medical?->blood_type }}" @disabled(!$isDoctor) class="mt-2 w-full rounded-xl border border-slate-200 p-3"></label>@foreach(['allergies'=>'Alergias','conditions'=>'Padecimientos','medications'=>'Medicamentos actuales','surgeries'=>'Cirugías previas','notes'=>'Observaciones'] as $name=>$label)<label class="text-xs font-bold {{ $name==='notes'?'md:col-span-2':'' }}">{{ $label }}<textarea name="{{ $name }}" rows="3" @disabled(!$isDoctor) class="mt-2 w-full rounded-xl border border-slate-200 p-3">{{ $medical?->{$name} }}</textarea></label>@endforeach</div>@if($isDoctor)<div class="mt-5 text-right"><button class="rounded-xl bg-[#7065f0] px-5 py-3 text-sm font-bold text-white">Guardar antecedentes</button></div>@endif</form>
    @elseif($tab==='odontograma')
        <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-bold">Odontograma</h2><p class="text-xs text-slate-400">Selecciona una pieza para registrar su estado.</p><div class="mt-6 grid grid-cols-8 gap-2 lg:grid-cols-16">@foreach(range(1,32) as $tooth)@php $entry=$teeth->get($tooth);$status=$entry?->status??'Sano';@endphp<button type="button" @if($isDoctor) onclick="pickTooth({{ $tooth }},'{{ $status }}',@js($entry?->notes??''))" @endif class="aspect-square rounded-xl border text-xs font-bold {{ $colors[$status] }}">{{ $tooth }}</button>@endforeach</div><div class="mt-5 flex flex-wrap gap-3">@foreach($colors as $label=>$class)<span class="text-[10px] text-slate-500"><i class="mr-1 inline-block h-3 w-3 rounded border {{ $class }}"></i>{{ $label }}</span>@endforeach</div>@if($isDoctor)<form method="POST" action="{{ route('pacientes.odontogram.update',$patient) }}" class="mt-6 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-[90px_180px_1fr_auto]">@csrf @method('PUT')<input id="tooth" type="number" name="tooth_number" min="1" max="32" required placeholder="Pieza" class="rounded-xl border border-slate-200 p-3"><select id="tooth-status" name="status" class="rounded-xl border border-slate-200 p-3">@foreach(array_keys($colors) as $status)<option>{{ $status }}</option>@endforeach</select><input id="tooth-notes" name="notes" placeholder="Notas de la pieza" class="rounded-xl border border-slate-200 p-3"><button class="rounded-xl bg-[#7065f0] px-4 text-sm font-bold text-white">Actualizar</button></form><script>function pickTooth(n,s,x){tooth.value=n;document.getElementById('tooth-status').value=s;document.getElementById('tooth-notes').value=x}</script>@endif</section>
    @else
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="border-b p-5"><h2 class="font-bold">Historial de citas</h2></div><div class="divide-y">@forelse($patient->appointments as $a)<div class="flex items-center gap-4 p-5"><div class="rounded-xl bg-slate-50 p-2 text-center"><b>{{ $a->date->format('d') }}</b><small class="block">{{ $a->date->locale('es')->isoFormat('MMM') }}</small></div><div class="flex-1"><p class="font-semibold">{{ $a->tipo }}</p><p class="text-xs text-slate-400">{{ date('H:i',strtotime($a->time)) }} · {{ $a->dentist?->nombre }}</p></div><span class="text-xs">{{ $a->estado }}</span></div>@empty<div class="p-12 text-center text-sm text-slate-400">Sin citas.</div>@endforelse</div></section>
    @endif
</div>
@endsection
